### ISSUE TITLE
FilePicker not working on Linux+Snapcraft

### ISSUE THREAD

**Issue by ariejan** [miguelpruivo/flutter_file_picker#1010]
**Describe the bug**
Running a debug or release build on Linux (`flutter run -d linux`) and the file picker works like a charm 🎉 
When I follow the (Flutter Linux deployment guide)[https://docs.flutter.dev/deployment/linux], which uses Snapcraft, the file picker does not show up at all. I'm also not able to get any kind of logging out of the "snapped" build. 

**Platform**

- [x] Desktop Linux bundled as Snapcraft

**Platform OS version**
Latest up-to-date Ubuntu Desktop 22.04 with flutter-stable (2.10.3) and latest flutter_file_picker 4.5.1. 

**How are you picking?**
```
    FilePickerResult? result = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowMultiple: false,
      allowedExtensions: ['txt'],
    );
```

**Details to reproduce the issue**
Create a Linux Desktop app; package it with Snapcraft as per the instructions linked above; Install snap; Run app. Note, without bundling the app as a Snap, the file picker works as expected.

**Error Log**
I can't get anything out of the snap-run app I'm afraid :-(

**Comment by mnipritom** [comment]
Apart from AppImages, both Snap and Flatpak builds suffer from multitude of issues while using this package. It's how they access the file system within the scope of containment, is causing these.

**Comment by ariejan** [comment]
@mnipritom that's interesting. There's the (home interface)[https://snapcraft.io/docs/home-interface] that might be helpful here in the case of Snap. I've found (Signal Desktop's snapcraft.yaml)[https://github.com/snapcrafters/signal-desktop/blob/master/snap/snapcraft.yaml] which might contain some pointers on how to get this working. I _think_ I have the `home` plug enabled already, but I'll have to double-check later when I have my linux box available. 
Please, keep this issue open for a while longer, I'll report back if I can get this to work.

**Comment by mnipritom** [comment]
I'm looking for pointers as well. 

I don’t know if these universal packaging formats are within the scope of this package, so I was hesitant to ask. Then I see this issue pop up.

**Comment by ariejan** [comment]
Okay, adding the `home` plug didn't make any difference at first. As it turns out the `zentity` command is used to open GTK dialogs. You'll need to add it as a part to your `snapcraft.yaml`, like so:

```
apps:
  txdx:
    command: txdx
    extensions: [flutter-stable] 
    slots:
      - dbus-txdx
    plugs:
      - network
      - home

parts:
  zenity:
    plugin: nil
    stage-packages:
      - zenity

  txdx:
    after:
      - zenity
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
```
Since it's only used on runtime the `after` can probably be omitted.
