### ISSUE TITLE
Cannot open file - Android physical device

### ISSUE THREAD

**Issue by alexda12** [miguelpruivo/flutter_file_picker#316]
Thank you for an excellent plugin - we have been using this since 1.2.0 and thankful for your continued work on this plugin.

**Describe the bug**
Trying to open a file on a physical android device fails with : 

> FileSystemException: Cannot open file, path = 'MyFile (1).xlsx' (OS Error: No such file or directory, errno = 2)

The file we are trying to open exists on OneDrive. If we copy the file locally (On the device) - there is no issue. Also - we can open the same file in iOS and there is no issue.

**Issue details**

Platform Android
Version of Flutter  1.12.13 hotfix 5 
(We cannot upgrade past this version because of 1 or more issues of the framework that have not been fixed after this release)

We have added : 

android:requestLegacyExternalStorage="true" 

To our android manifest.

Also - we have set our CompileSDK version to 29.

**Comment by miguelpruivo** [comment]
Hi, this looks like an edge case for that particular file.  Does that happen with other files when picking from one drive?

**Comment by alexda12** [comment]
hey there -  thanks for the fast reply

No , its not a particular file type or file name etc - its just accessing on Android on a OneDrive cloud (Any files) ... Only happens on Android and not on iOS ... 

Its because the full path is not returned via your plugin, just the file name and so my routine (I am opening an Excel file and reading the contents, fails) .... I managed to use flutter_document_picker - this works ... and returns the full path ...

**Comment by miguelpruivo** [comment]
Looks like using `Intent.ACTION_OPEN_DOCUMENT` instead o `Intent.ACTION_GET_CONTENT` may result in desired behavior. I'll create a separate branch so you can try it out and let me know if it's working for you.

**Comment by alexda12** [comment]
Cool , send me the branch when you get a chance and I will test it for you - many thanks..

**Comment by miguelpruivo** [comment]
Sure @alexda12, here you have it, just replace your file_picker with:
```
file_picker:
    git:
      url: https://github.com/miguelpruivo/flutter_file_picker.git
      ref: feature/open_document
```

**Comment by alexda12** [comment]
That fails for me in pubspec trying to resolve dependencies , i have : 
```

file_picker:
      git:
        url:  https://github.com/miguelpruivo/flutter_file_picker.git 
        ref:  fix/open_document

```
and it gives : 

> Could not find a file named "pubspec.yaml" in https://github.com/miguelpruivo/flutter_file_picker.git 68416c7cde6091b14fd05416e949270de45fe4af.
> pub get failed (1; Could not find a file named "pubspec.yaml" in https://github.com/miguelpruivo/flutter_file_picker.git 68416c7cde6091b14fd05416e949270de45fe4af.)

**Comment by miguelpruivo** [comment]
Sorry, I forgot the path:
```
  file_picker:
    git:
      url:  https://github.com/miguelpruivo/flutter_file_picker.git 
      ref:  fix/open_document
      path: file_picker/
```
