### ISSUE TITLE
MissingPluginException on release mode

### ISSUE THREAD

**Issue by yeras-is** [miguelpruivo/flutter_file_picker#651]
**Describe the bug**
When I build release app on android,  app crashes on start with MissingPluginException. On debug mode everything works well.

**Platform**
- Android

**Pubspec**
```
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.1
  asuka: ^2.0.0-nullsafety.2
  provider: ^5.0.0
  basic_utils: ^3.0.0-nullsafety.0
  get_it: ^6.0.0
  font_awesome_flutter: ^9.0.0-nullsafety
  pin_code_text_field: ^1.8.0
  flutter_secure_storage: ^4.0.0
  local_auth: ^1.1.0
  file_picker: ^3.0.0


dependency_overrides:
  intl: ^0.17.0
  hive_flutter: ^1.0.0
  hive: ^2.0.0
  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.1
  build_runner: ^1.10.2
```

**Details to reproduce the issue**
build app in release mode

**Error Log**
```
Installing build/app/outputs/flutter-apk/app.apk...
E/flutter (30353): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
E/flutter (30353): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156)
E/flutter (30353): <asynchronous suspension>
E/flutter (30353): #1      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:139)
E/flutter (30353): <asynchronous suspension>
E/flutter (30353): #2      registerServices (package:oncom/main.dart:32)
E/flutter (30353): <asynchronous suspension>
E/flutter (30353): #3      main (package:oncom/main.dart:16)
E/flutter (30353): <asynchronous suspension>
```

**Flutter Version details**
Flutter (Channel stable, 2.0.1, on macOS 11.2.3 20D91 darwin-arm, locale ru-KZ)
