### ISSUE TITLE
Temporary file could not be created.

### ISSUE THREAD

**Issue by whedamd** [miguelpruivo/flutter_file_picker#997]
flutter: [MethodChannelFilePicker] Platform exception: PlatformException(file_picker_error, Temporary file could not be created, Error Domain=NSItemProviderErrorDomain Code=-1000 "Cannot load representation of type public.item" UserInfo={NSLocalizedDescription=Cannot load representation of type public.item}, null)

Platform: iOS

**Comment by gabdsg** [comment]
Same problem here

**Comment by nobezawa** [comment]
Have the same problem.

my version
```yaml
file_picker:
    dependency: "direct main"
    description:
      name: file_picker
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.5.1"
```

Execution environment
```
iPhone Simulator: iPhone11
iOS: 15.2
```
